### ISSUE TITLE
HasFlag(RawKeyboardFlags.Down) alsways returns true

### ISSUE THREAD

**Issue by joosthoi1** [mfakane/rawinput-sharp#9]
Like the title says, if you have a RawKeyboardFlags variable and you use HasFlag(RawKeyboardFlags.Down) on it, it will always return true, this is due to RawKeyboardFlags.Down being 0 in the enum and the bitwise logic that goes into checking if it has the flag. In flag enums this should only ever be used as a flag "everything".

In my own code I temporarily use if (flags.Equals(RawKeyboardFlags.Down) || flags.Equals(RawKeyboardFlags.LeftKey));
But it should be fixed

**Comment by mfakane** [comment]
To be honest, `RawKeyboardFlags` is a wrapper for `RI_KEY_*`, and `RawKeyboardFlags.Down` has a same value as `RI_KEY_MAKE`.

> `Flags`
>
> Type: **USHORT**
>
> Flags for scan code information. It can be one or more of the following:
> Value | Meaning
> -- | --
> RI_KEY_MAKE 0 | The key is down.
> RI_KEY_BREAK 1 | The key is up.
> RI_KEY_E0 2 | The scan code has the E0 prefix.
> RI_KEY_E1 4 | The scan code has the E1 prefix.
>
> <cite>[RAWKEYBOARD structure (winuser.h) - Win32 apps | Microsoft Docs](https://docs.microsoft.com/en-us/windows/win32/api/winuser/ns-winuser-rawkeyboard)</cite>

So, if you want to check the key event is a key-down event, actually you need to use `!flags.HasFlag(RawKeyboardFlags.Up)` instead.
I know that it's so confusing, so I'm thinking to rename it to `RawKeyboardFlags.None` or something similar to make the meaning more clearly understandable.

**Comment by mfakane** [comment]
Renamed in https://github.com/mfakane/rawinput-sharp/releases/tag/0.0.4
